### ISSUE TITLE
DataRequestCallback_t()

### ISSUE THREAD

**Issue by happysmile09** [labautomation/LIN_stack#1]
I cant find any function declaration for this. Please fix

**Comment by eLimones** [comment]
DataRequestCallback_t is a function pointer type not a function itself.
It is used to allow signature check at compile time when calling the function
linTask_setReceivedCallback() (which hasn't been implemented yet) 

If what you want is to add task to the lin daemon do this 

//declare callback functions  with the same signature as  DataReceivedCallback_t
//which is defined lin_type.h as : 
// typedef void (*DataReceivedCallback_t)( uint8_t header, uint8_t *data);

uint8_t* myTxCallback(uint8_t header);

// declare a lin_task structure and add the pointer to function in the callback field
lin_task_t myTxLinTask = {0x9,LIN_TASK_DIR_REQUEST,4,myTxCallback};

main(){
 ... 
 ...
    //add task to daemon by passing the pointer of the task structure
    lin_slave_task_add(myTxLinTask);
}

//Define your callback function 
uint8_t*  myTxCallback(uint8_t header){
        //whaterver you want to do when the lin bus asks for data 
        return pointer_to_data_to_send;
}

**Comment by happysmile09** [comment]
Thanks for your answer. One more question is that did you implement the function to read LDF file?

**Comment by eLimones** [comment]
sorry, this stack does not have that functionality, anyway  we can add it for the next version along with the LIN 2.0 compliance
